site_name: Примеры кода от DJWOMS
theme:
  name: material
  features:
    - navigation.instant
  logo: assets/logo.png
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Выключить свет

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Включить свет
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@DjangoSchool
    - icon: fontawesome/brands/telegram
      link: https://t.me/django_school
nav:
  - Главная: index.md
  - Django:
      - Админка:
          - Переопределить сохранение формы admin Inline: django/admin/custom_saving_inline.md


