site_name: Примеры кода от DJWOMS
theme:
  name: material
  features:
    - navigation.instant
  logo: assets/logo.png
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Выключить свет

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Включить свет
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@DjangoSchool
    - icon: fontawesome/brands/telegram
      link: https://t.me/django_school
nav:
  - Главная: index.md
  - Django:
      - Админка:
          - Переопределить сохранение формы admin Inline: django/admin/custom_saving_inline.md
      - Работа с файлами:
          - Редактировать изображение перед сохранением: django/files/make_thumbnail.md
  - Django Rest Framework:
      - ORM:
          - Сократить количество запросов в БД (Foreign Key): django_rest_framework/orm/select_related.md
  - FastAPI:
      - Depends:
          - Реализация permissions и параметры Depends: fastapi/depends/permissions.md
  - E-commerce - интернет магазин видеоигр:
      - Схема БД games: ecommerce_my_steam/assets/games_db.svg
      - Схема БД users: ecommerce_my_steam/assets/users_db.svg
      - Схема БД payments: ecommerce_my_steam/assets/payments_db.svg


